[camera_info]
vendor_name = "John Doe                   "
model_name = "Fake Camera                  "
firmware_version = 1
focal_length = 8.0
sensor_size_h = 6.0
sensor_size_v = 4.0
resolution_h = 1920
resolution_v = 1080
lens_id = 0
flags = 0
cam_definition_version = 1
cam_definition_uri = "http://example.com/camera_definition.xml"

[camera_position]
x = 0.0
y = 0.0
z = 0.0
roll = 0.0
pitch = 0.0
yaw = 0.0

[gstreamer]
#_pipeline = [
#    "videotestsrc pattern=ball flip=true is-live=true num-buffers=1000 ! video/x-raw,framerate=10/1 !  tee name=t",
#    "t.",
#    "queue leaky=2 ! valve name=stream_valve drop=True ! video/x-raw,format=I420,width=640,height=480",
#    "videoconvert",
#    "x264enc tune=zerolatency",
#    "rtph264pay ! udpsink host=127.0.0.1 port=5000",
#    "t.",
#    "queue leaky=2 ! valve name=image_valve drop=True",
#    "videoconvert ! videorate drop-only=true ! video/x-raw,framerate=5/1,format=(string)BGR",
#    "videoconvert ! appsink name=mysink emit-signals=true  sync=false async=false  max-buffers=2 drop=true ",
#    "t.",
#    "intervideosink channel=video-capture-channel",
##    "queue leaky=2 ! valve name=video_valve drop=False ! x264enc tune=zerolatency ! mp4mux ! filesink location=video.mp4",
#]
# https://gstreamer.freedesktop.org/documentation/videorate/index.html?gi-language=c
pipeline = [
#    "videotestsrc pattern=ball is-live=true ! video/x-raw,framerate=10/1 !  autovideosink",
    "videotestsrc pattern=ball is-live=true ! video/x-raw,width=640,height=480,framerate=30/1 !  tee name=t",

    "t.",
    'queue ! autovideosink',

    "t.",
    'queue leaky=2 ! intervideosink channel=channel_0 ',

    "t.",
    'queue leaky=2 ! intervideosink channel=channel_1 ',

    "t.",
    'queue leaky=2 ! intervideosink channel=channel_3 ',

    "t.",
    "queue leaky=2 ! valve name=image_valve drop=True",
    "videoconvert ! videorate drop-only=true ! video/x-raw,framerate=10/1,format=(string)BGR",
    "videoconvert ! appsink name=mysink emit-signals=true  sync=false async=false  max-buffers=2 drop=true ",
    ]

#        command = ['intervideosrc channel=video-capture-channel  ',
#                                 'videoconvert',
#                                 f'video/x-raw,width=640,height=480,framerate={fps}/1',
#                                 # f'videorate drop-only=true ! video/x-raw,width=640,height=480,framerate={fps}/1',
#                                 # 'autovideosink',
#                                 'videoconvert',
#                                 f'x264enc bitrate={bitrate}',
#                                 'mp4mux ! filesink location={}'.format(filename),
#                                 ]