[camera_info]
vendor_name = "John Doe                   "
model_name = "Fake Camera                  "
firmware_version = 1
focal_length = 8.0
sensor_size_h = 6.0
sensor_size_v = 4.0
resolution_h = 1920
resolution_v = 1080
lens_id = 0
flags = 0
cam_definition_version = 1
cam_definition_uri = "http://example.com/camera_definition.xml"

[camera_position]
x = 0.0
y = 0.0
z = 0.0
roll = 0.0
pitch = 0.0
yaw = 0.0

[gstreamer]

src_pipeline = [
#    "videotestsrc pattern=ball is-live=true ! video/x-raw,framerate=10/1 !  autovideosink",
#    "videotestsrc pattern=ball is-live=true ! video/x-raw,width=640,height=480,framerate=30/1 !  tee name=t",
    "videotestsrc  ! video/x-raw,width=640,height=480,framerate=30/1 !  tee name=t",
#    "videotestsrc ! video/x-raw,width=640,height=480,framerate=30/1 !  tee name=t",

    "t.",
    'queue ! autovideosink',

    "t.",
    'queue leaky=2 ! intervideosink channel=channel_0',

    "t.",
    'queue leaky=2 ! intervideosink channel=channel_1',

    "t.",
    'queue leaky=2 ! videoconvert ! videorate drop-only=true ! intervideosink channel=channel_2 ',

#    "t.",
##    'queue leaky=2',
##    'video/x-raw,format=RGB,width=640,height=480 ',
#    'videoconvert ! videoscale ! video/x-raw,format=RGB,depth=8,width=640,height=480 ',
#    'rtpvrawpay ! udpsink host=127.0.0.1 port=5100',

    #
    #    "t.",
    #    "queue leaky=2 ! valve name=image_valve drop=True",
    #    "videoconvert ! videorate drop-only=true ! video/x-raw,framerate=10/1,format=(string)BGR",
    #    "videoconvert ! appsink name=mysink emit-signals=true  sync=false async=false  max-buffers=2 drop=true ",
    ]

ai_pipeline = [
            'intervideosrc channel=channel_0',
            # 'videotestsrc pattern=ball num-buffers={num_buffers}',
            'videoconvert ! videoscale ! video/x-raw,width={width},height={height},framerate={fps}/1,format=(string)BGR',
            'appsink name=ai_sink emit-signals=true  sync=false async=false  max-buffers=2 drop=true ',
        ]

jpg_pipeline = [
            'intervideosrc channel=channel_1  ',
            # 'videotestsrc pattern=ball num-buffers={num_buffers}',
            'videoconvert ! videoscale ! video/x-raw,width={width},height={height},framerate={fps}/1',
            'queue',
            'jpegenc quality={quality}',  # Quality of encoding, default is 85
            # "queue",
            'appsink name=mysink emit-signals=True max-buffers=1 drop=True',
        ]

# todo add video save pipeline

# streaming pipelines

h264_pipeline = [
            'intervideosrc channel=channel_2',
            # 'videotestsrc pattern=ball flip=true is-live=true ! video/x-raw,framerate={fps}/1',
            'queue',
            'videoscale ! video/x-raw,width={width},height={height},framerate={fps}/1',
            # 'video/x-raw,format=I420,width={width},height={height}',
            # 'queue leaky=2 ! video/x-raw,format=I420,width={width},height={height}',
            # 'videoconvert',
            # 'queue',
            # 'x264enc tune=zerolatency noise-reduction=10000 bitrate=2048 speed-preset=superfast',
            'x264enc tune=zerolatency',
            'rtph264pay ! udpsink host=127.0.0.1 port={port}',
        ]

#gst-launch-1.0 videotestsrc ! video/x-raw,format=RGB,width=640,height=480 ! rtpvrawpay ! udpsink host=127.0.0.1 port=5000
raw_pipeline = [
            'intervideosrc channel=channel_2',
            # 'videotestsrc pattern=ball flip=true is-live=true ! video/x-raw,framerate={fps}/1',
            'queue',
#            'videoscale ! video/x-raw,format=RGB,width={width},height={height},framerate={fps}/1',
#            'videoscale'
            'videoconvert ! videoscale ! video/x-raw,format=RGB,depth=8,width={width},height={height}',
            'rtpvrawpay ! udpsink host=127.0.0.1 port={port}',
#            'videoconvert ! videoscale ! video/x-raw,format=RGB,depth=8,width=640,height=480 ',
#            'rtpvrawpay ! udpsink host=127.0.0.1 port=5100',
        ]